version: '3'

services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - pgdata:/data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: holiday

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata: